require 'active_record'
require 'active_record/connection_adapters/postgresql_adapter'
require "updateable_views_inheritance/version"
require "updateable_views_inheritance/active_record_extensions"
require 'updateable_views_inheritance/postgresql_adapter'
